name: pagmelhor-app
services:
  # api:
  #   container_name: api
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "4000:4000"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - postgres
  #     - redis
  #     - rabbitmq
  #   restart: unless-stopped
  #   networks:
  #     - pagmelhor-backend-network

  postgres:
    container_name: postgres
    image: postgres:16.0-alpine
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PORT=${DB_PORT}
    networks:
      - pagmelhor-backend-network

  redis:
    container_name: redis
    image: redis:6.0.8-alpine
    ports:
      - 6379:6379
    networks:
      - pagmelhor-backend-network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13.7-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./.data/rabbitmq:/var/lib/rabbitmq
    networks:
      - pagmelhor-backend-network

  redis-insight:
    container_name: redis-insight
    image: redislabs/redisinsight:latest
    profiles: [debug]
    volumes:
      - ./.data/redis-insight:/data
    ports:
      - 5540:5540
    depends_on:
      - redis
    networks:
      - pagmelhor-backend-network

networks:
  pagmelhor-backend-network:
    name: pagmelhor-backend-network
    driver: bridge
